seev/apps/order/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.go_ord_home, name='go_ord_home'),
    re_path(r'^find-oppo/$', views.find_oppo_by_num, name='find_oppo_by_num'),
    re_path(r'^create-order/$', views.create_order, name='create_order'),
    re_path(r'^config-home/$', views.go_ord_config_home,
            name='go_ord_config_home'),
    re_path(r'^find-ord/$', views.find_ord_by_num, name='find_ord_by_num'),
    re_path(r'^auth-ord/$', views.auth_access_order, name='auth_access_order'),
    re_path(r'^exit-ord/$', views.exit_order, name='exit_order'),
    re_path(r'^config-site/$', views.go_site_config, name='go_site_config'),
    re_path(r'^add-new-site/$', views.add_new_site, name='add_new_site'),
    re_path(r'^rm-site/$', views.rm_site, name='rm_site'),
    re_path(r'^build-pr/$', views.go_build_pr, name='go_build_pr'),
    re_path(r'^add-new-pr/$', views.add_pr_to_basket, name='add_pr_to_basket'),
    re_path(r'^del-pr/$', views.del_pr_in_site, name='del_pr_in_site'),
    re_path(r'^edit-svc/$', views.go_svc_config, name='go_svc_config'),
    re_path(r'^save-svc/$', views.save_svc_config, name='save_svc_config'),
    re_path(r'^valid-ord/$', views.do_ord_valid, name='do_ord_valid'),
    re_path(r'^ord-summ/$', views.go_ord_summary, name='go_ord_summary'),
    re_path(r'^do-price/$', views.do_site_price, name='do_site_price'),
    re_path(r'^sub-ord/$', views.do_ord_submit, name='do_ord_submit'),
    re_path(r'^can-ord/$', views.do_ord_cancel, name='do_ord_cancel'),
]

seev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('seev.apps.core.urls')),
    path('catalog/', include('seev.apps.catalog.urls')),
    path('order/', include('seev.apps.order.urls')),
]

handler404 = 'seev.apps.core.views.go_bad_view'
handler500 = 'seev.apps.core.views.go_bad_view'

seev/apps/core/models.py
"""
Model definitions in core app
"""

import uuid

from django.db import models
from django.utils.timezone import now

from seev.apps.utils.country import UnoCountry
from seev.apps.utils.state import UnoState


class UnoClient(models.Model):
    client_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    le_id = models.UUIDField(
        'Legal Entity ID', default=uuid.uuid4, editable=False)
    ctg_name = models.CharField(
        'Catalog Name', max_length=32, unique=True, editable=False)
    entity_name = models.CharField('Entity/Company Name', max_length=255)
    country = models.CharField(
        'Country', max_length=64, default=UnoCountry.get_default_cty, choices=UnoCountry.get_cty_code_list())
    trade_ticker = models.CharField(
        'Stock Ticker Symbol', max_length=12, null=True, blank=True)
    contact_email = models.EmailField('Contact Email')
    contact_phone = models.SlugField(
        'Contact Phone', max_length=10, help_text='Must be a valid number in the U.S.')
    signature_letter = models.BinaryField('Signature Letter of Agreement')
    active = models.BooleanField(default=False, editable=False)
    status = models.CharField('Status', max_length=16,
                              default='Pending', editable=False, null=False)
    summary = models.TextField('Business Summary', null=True, blank=True)
    website = models.CharField(
        'Business Website', max_length=255, null=True, blank=True)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'UNO_CLIENT'


class UnoCredentials(models.Model):
    credentials_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    client = models.ForeignKey(UnoClient, on_delete=models.CASCADE, null=False)
    username = models.CharField(
        'Username', max_length=32, null=False, unique=True)
    password_salt = models.CharField(max_length=8, editable=False)
    password_hash = models.CharField(
        max_length=1024, editable=False, null=False)
    recovery_email = models.EmailField(
        'Recovery Email', help_text='Email used to reset password', unique=True)
    pin = models.PositiveSmallIntegerField(
        'PIN', help_text='PIN is required to reset password')
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'UNO_CREDENTIALS'


class UnoApproval(models.Model):
    approval_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    client = models.ForeignKey(
        UnoClient, on_delete=models.CASCADE, null=False, blank=False)
    action = models.CharField('Action', max_length=16, choices=[
        ('AP', 'Approve Request'),
        ('DE', 'Deny Request'),
        ('RV', 'Revoke Business'),
        ('RI', 'Reinstate Business'),
    ], null=False, blank=False)
    message = models.TextField('Message/Comment', null=True, blank=False)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'UNO_APPROVAL'


class UnoCustomer(models.Model):
    customer_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    le_id = models.UUIDField('Customer Entity ID',
                             default=uuid.uuid4, editable=False)
    client = models.ForeignKey(UnoClient, on_delete=models.CASCADE, null=False)
    customer_name = models.CharField('Customer Name', max_length=255)
    contact_email = models.EmailField('Contact Email')
    country = models.CharField(
        'Country', max_length=64, default=UnoCountry.get_default_cty, choices=UnoCountry.get_cty_code_list())
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'UNO_CUSTOMER'


class UnoOpportunity(models.Model):
    opportunity_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    opportunity_number = models.UUIDField(
        'Opportunity Number', default=uuid.uuid4, editable=False)
    client = models.ForeignKey(UnoClient, on_delete=models.CASCADE, null=False)
    customer = models.ForeignKey(
        UnoCustomer, on_delete=models.CASCADE, null=False)
    active = models.BooleanField(default=True, editable=False)
    discount_nrc = models.CharField('Non-recurring Discount', max_length=16, choices=[
        ('0', 'No Discount'),
        ('5', '5% Discount'),
        ('10', '10% Discount'),
        ('15', '15% Discount'),
        ('20', '20% Discount'),
        ('25', '25% Discount'),
        ('30', '30% Discount'),
    ], null=False, blank=False)
    discount_mrc = models.CharField('Monthly Discount', max_length=16, choices=[
        ('0', 'No Discount'),
        ('5', '5% Discount'),
        ('10', '10% Discount'),
        ('15', '15% Discount'),
        ('20', '20% Discount'),
        ('25', '25% Discount'),
        ('30', '30% Discount'),
    ], null=False, blank=False)
    deal_count = models.PositiveSmallIntegerField(
        'Deal Count', editable=False, default=0)
    deal_limit = models.PositiveSmallIntegerField('Deal Limit', default=1)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'UNO_OPPORTUNITY'


class UnoOrder(models.Model):
    order_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    order_number = models.UUIDField('Order Number', editable=False)
    client = models.ForeignKey(UnoClient, on_delete=models.CASCADE, null=False)
    customer = models.ForeignKey(
        UnoCustomer, on_delete=models.CASCADE, null=False)
    opportunity = models.ForeignKey(
        UnoOpportunity, on_delete=models.CASCADE, null=False)
    status = models.CharField('status', max_length=16, choices=[
        ('CL', 'Cancelled'),
        ('SM', 'Submitted'),
        ('IV', 'Invalidated'),
        ('OD', 'Ordered'),
        ('CP', 'Completed'),
    ], null=False, blank=False)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)
    last_update_time = models.DateTimeField(
        'Timestamp of Last Update', default=now, editable=False, null=False)

    class Meta:
        db_table = 'UNO_ORDER'


class UnoSite(models.Model):
    site_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    location_id = models.UUIDField(
        'Location ID', default=uuid.uuid4, editable=False)
    customer = models.ForeignKey(
        UnoCustomer, on_delete=models.CASCADE, null=False)
    address_1 = models.CharField(
        'Address Line 1', max_length=512, null=False, blank=False)
    address_2 = models.CharField('Address Line 2', max_length=128, null=True)
    address_3 = models.CharField('Address Line 3', max_length=128, null=True)
    city = models.CharField('City', max_length=64)
    state = models.CharField('State or Province', max_length=64)
    zipcode = models.CharField('Zipcode', max_length=64)
    country = models.CharField('Country', max_length=256, null=False)
    is_virtual = models.BooleanField(default=False)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'UNO_SITE'


class SeevEventLog(models.Model):
    """
    Server logging table
    """
    log_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    log_time = models.DateTimeField(
        'Event Time', default=now, editable=False, null=False)
    log_level = models.CharField('Log Level', max_length=4, choices=[
        ('0', 'Unknown'),
        ('1', 'Debug'),
        ('2', 'Warn'),
        ('3', 'Error'),
        ('4', 'Fatal'),
    ], null=False, blank=False, editable=False)
    order_id = models.UUIDField('Order ID', editable=False, null=True)
    user_id = models.UUIDField('User ID', editable=False, null=True)
    log_desc = models.TextField('Log Description', max_length=1024, null=True)
    stack_trace = models.TextField('Stack Trace', max_length=4000, null=True)

    class Meta:
        db_table = 'SEEV_EVENT_LOG'

seev/apps/order/models.py
"""
Model definitions in order app
"""

import uuid

from django.db import models
from django.utils.timezone import now

from seev.apps.core.models import (
    UnoClient, UnoSite, UnoCustomer, UnoOpportunity)


class PtaBasket(models.Model):
    basket_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    client = models.ForeignKey(UnoClient, on_delete=models.CASCADE, null=False)
    customer = models.ForeignKey(
        UnoCustomer, on_delete=models.CASCADE, null=False)
    is_locked = models.BooleanField(default=False)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'PTA_BASKET'


class PtaOrderInstance(models.Model):
    order_instance_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    order_number = models.UUIDField(
        'Order Number', default=uuid.uuid4, editable=False)
    order_name = models.CharField(
        'Order Name', max_length=32, default=None, null=True)
    secret = models.CharField('Order Secret', max_length=64, default=None)
    client = models.ForeignKey(UnoClient, on_delete=models.CASCADE, null=False)
    customer = models.ForeignKey(
        UnoCustomer, on_delete=models.CASCADE, null=False)
    opportunity = models.ForeignKey(
        UnoOpportunity, on_delete=models.CASCADE, null=False)
    basket = models.ForeignKey(
        PtaBasket, on_delete=models.SET_NULL, null=True)
    status = models.CharField('Status', max_length=16, choices=[
        ('IN', 'Initiated'),
        ('IP', 'In Progress'),
        ('VA', 'Validated'),
        ('FL', 'Finalized'),
        ('FZ', 'Frozen'),
        ('EX', 'Expired'),
        ('VD', 'Voided'),
    ], null=False, blank=False)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'PTA_ORDER_INSTANCE'


class PtaSite(models.Model):
    pta_site_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    site_name = models.CharField('Site Name', max_length=128, null=True)
    site = models.ForeignKey(UnoSite, on_delete=models.SET_NULL, null=True)
    order_instance = models.ForeignKey(
        PtaOrderInstance, on_delete=models.CASCADE, null=False)
    is_valid = models.BooleanField(default=False)
    is_priced = models.BooleanField(default=False)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'PTA_SITE'


class PtaBasketItem(models.Model):
    basket_item_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    parent_id = models.UUIDField('Parent Item ID', editable=False, null=True)
    basket = models.ForeignKey(PtaBasket, on_delete=models.CASCADE, null=False)
    ctg_doc_id = models.UUIDField(
        'Catalog Item ID', editable=False, null=False)
    itemcode = models.CharField('Item Code', max_length=32, null=False)
    serial = models.PositiveSmallIntegerField(
        'Serial Number', default=0, null=True)
    pta_site = models.ForeignKey(PtaSite, on_delete=models.CASCADE, null=False)
    is_valid = models.BooleanField(default=False)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'PTA_BASKET_ITEM'


class PtaItemLeaf(models.Model):
    leaf_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    basket_item = models.ForeignKey(
        PtaBasketItem, on_delete=models.CASCADE, null=False)
    basket = models.ForeignKey(PtaBasket, on_delete=models.CASCADE, null=False)
    leaf_name = models.CharField(
        'Leaf Name', max_length=32, null=False, unique=False)
    leaf_value = models.CharField('Leaf Value', max_length=512, default=None)

    class Meta:
        db_table = 'PTA_ITEM_LEAF'


class PtaPriceLine(models.Model):
    price_line_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    basket_item = models.ForeignKey(
        PtaBasketItem, on_delete=models.CASCADE, null=False)
    item_leaf = models.ForeignKey(
        PtaItemLeaf, on_delete=models.CASCADE, null=False)
    charge_type = models.CharField('Charge Type', max_length=16, choices=[
        ('QUAN', 'Quantity Based'),
        ('SPEC', 'Specification Based'),
        ('ONTM', 'One-Time Charge'),
    ], null=False, blank=False)
    mrc_charge = models.DecimalField(
        max_digits=20, decimal_places=2, default=0.00, null=True)
    nrc_charge = models.DecimalField(
        max_digits=20, decimal_places=2, default=0.00, null=True)
    creation_time = models.DateTimeField(
        'Timestamp of Creation', default=now, editable=False, null=False)

    class Meta:
        db_table = 'PTA_PRICE_LINE'

seev/apps/order/templates/order/base.html
<!-- Order base template -->
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'order/css/main.min.css' %}">
{% endblock css %}

{% block content %}
<div id="ord-main-wrapper">
	{% block ordContent %}
	{% endblock ordContent %}
</div>
{% endblock content %}

{% block snackData %}
{% if snack_data is not None and snack_data != '' %}
{{ snack_data }}
{% endif %}
{% endblock snackData %}

{% block js %}
<script src="{% static 'order/js/main.js' %}"></script>
<script src="{% static 'order/js/forms.js' %}"></script>
{% endblock js %}

seev/apps/order/templates/order/order-base.html
<!-- Order configuration template -->
{% extends 'order/base.html' %}
{% load static %}

{% block ordContent %}
<!-- Data -->
<aside style="display: none;">
	<div id="ord-data-order-number">{{ data_on }}</div>
	<div id="ord-data-order-status">{{ data_os }}</div>
	<div id="ord-data-order-dis" data-mrc="{{ ordMeta.order_dis_mrc }}" data-nrc="{{ ordMeta.order_dis_nrc }}"></div>
</aside>
<!-- Content -->
<div id="ord-config-head">
	<div id="ord-header-wrapper">
		<div id="order-number">Order # {{ ordMeta.order_number }}</div>
		<div id="order-name">Order Name: {{ ordMeta.order_name }}</div>
		<div id="ord-header-action-wrapper">
			<button type="button" class="order-icon-btn" onclick="showOrderPopup('ord-detail-popup')">
				<span>
					<img src="{% static 'order/images/icon-55.svg' %}" alt="view-icon">
					<span style="color: #283593;">View Details</span>
				</span>
			</button>
			<button type="button" class="order-icon-btn" onclick="showOrderPopup('ord-validation-popup', true)">
				<span>
					<img src="{% static 'order/images/icon-56.svg' %}" alt="validate-icon">
					<span style="color: #2E7D32;">Validate Order</span>
				</span>
			</button>
			<button type="button" class="order-icon-btn" onclick="showOrderPopup('ord-cancel-popup', true)">
				<span>
					<img src="{% static 'order/images/icon-57.svg' %}" alt="cancel-icon">
					<span style="color: #D84315;">Cancel Order</span>
				</span>
			</button>
		</div>
	</div>
</div>
<!-- Base scripts -->
<script src="{% static 'order/js/order.js' %}"></script>
<div id="ord-config-body">
	{% block ordConfBody %}
	{% endblock ordConfBody %}
</div>
<!-- Popup -->
<div class="black-overlay no-show"></div>
<!-- Order details -->
<div id="ord-detail-popup" class="seev-popup no-show">
	<div class="popup-head" style="margin-bottom: 3rem;">
		<img onclick="dismissOrderPopup('ord-detail-popup')" src="{% static 'icon-100.svg' %}" alt="close-icon">
	</div>
	<div>
		<div class="ord-detail-pop-row">
			<span>Oppor. #: </span>
			<span style="color: #B71C1C;">{{ ordMeta.opportunity_number }}</span>
		</div>
		<div class="ord-detail-pop-row">
			<span>Customer Name: </span>
			<span>{{ ordMeta.customer_name }}</span>
		</div>
		<div class="ord-detail-pop-row">
			<span>Business Client: </span>
			<span>{{ ordMeta.client_name }}</span>
		</div>
		<div class="ord-detail-pop-row">
			<span>Business Email: </span>
			<span>{{ ordMeta.client_email }}</span>
		</div>
		<div class="ord-detail-pop-row">
			<span>Business Phone: </span>
			<span>{{ ordMeta.client_phone }}</span>
		</div>
		<div class="ord-detail-pop-row">
			<span>Monthly Discount: </span>
			<span>{{ ordMeta.order_dis_mrc }}%</span>
		</div>
		<div class="ord-detail-pop-row">
			<span>Flat Discount: </span>
			<span>{{ ordMeta.order_dis_nrc }}%</span>
		</div>
		<div class="ord-detail-pop-row">
			<span>Order Status: </span>
			<span style="color: #4A148C;">{{ ordMeta.order_status }}</span>
		</div>
	</div>
</div>
<!-- Validation -->
<div id="ord-validation-popup" class="seev-popup no-show">
	<div class="popup-head" style="margin-bottom: 3rem;">
		<img onclick="dismissOrderPopup('ord-validation-popup')" src="{% static 'icon-100.svg' %}" alt="close-icon">
	</div>
	<div class="popup-body">
		<div>This will take you directly to the order home page, and all unsaved data will be lost. Are you sure to
			continue?</div>
		<div>
			<button onclick="submitOrderForm('ord-valid-form')" style="background-color: #43A047;" type="button"
				class="ord-pri-btn">Yes (Validate)</button>
			<button onclick="dismissOrderPopup('ord-validation-popup')" type="button" class="ord-pri-btn">No</button>
		</div>
	</div>
</div>
<!-- Cancellation -->
<div id="ord-cancel-popup" class="seev-popup no-show">
	<div class="popup-head" style="margin-bottom: 3rem;">
		<img onclick="dismissOrderPopup('ord-cancel-popup')" src="{% static 'icon-100.svg' %}" alt="close-icon">
	</div>
	<div class="popup-body">
		<div>You are about to cancel this order. This action cannot be reverted. Are you sure to continue?</div>
		<div>
			<button onclick="submitOrderForm('ord-cancel-form')" style="background-color: #D32F2F;" type="button"
				class="ord-pri-btn">Yes (Cancel)</button>
			<button onclick="dismissOrderPopup('ord-cancel-popup')" type="button" class="ord-pri-btn">No</button>
		</div>
	</div>
</div>
<!-- Float -->
<div class="seev-float-btn-group">
	<div style="background-color: #0D47A1;" class="seev-float-btn" onclick="exitOrder()">
		<img src="{% static 'order/images/icon-58.svg' %}" alt="exit-icon">
	</div>
	<div style="background-color: #B71C1C;" class="seev-float-btn float-above" onclick="navToConfigHome()">
		<img src="{% static 'order/images/icon-59.svg' %}" alt="home-icon">
	</div>
</div>
<!-- Hidden forms -->
<form style="display: none;" action="/order/exit-ord/" id="exit-ord-form" method="POST">
	{% csrf_token %}
</form>
<form id="ord-valid-form" action="/order/valid-ord/" method="post" novalidate style="display: none;">
	{% csrf_token %}
</form>
<form id="ord-cancel-form" action="/order/can-ord/" method="post" novalidate style="display: none;">
	{% csrf_token %}
</form>
{% endblock ordContent %}

seev/apps/order/templates/order/order-site.html
<!-- Order site configuration page -->
{% extends 'order/order-base.html' %}
{% load static %}

{% block ordConfBody %}
<section id="ord-add-site-sect">
	<h1 class="ord-config-title">Add New Site</h1>
	<div id="site-search-wrapper">
		<h2 class="ord-config-subtitle">Powered by Google Maps</h2>
		<div id="map-wrapper">
			<div id="ac-wrapper">
				<input type="text" id="ac-input" placeholder="Enter an address">
			</div>
			<div id="map"></div>
		</div>
	</div>
	<div id="site-details-wrapper">
		<h2 class="ord-config-subtitle">Address Details</h2>
		<form id="ord-site-addr-form" action="/order/add-new-site/" method="post">
			{% csrf_token %}
			<div id="addr-grid">
				<div class="addr-grid-inner-wrapper addr-long">
					<label for="site-name" class="addr-label">Location Name <span style="color: #D32F2F;">*</span></label>
					<input class="addr-grid-item" type="text" name="site_name" id="site-name" required>
				</div>
				<div class="addr-grid-inner-wrapper addr-long">
					<label for="addr-line-1" class="addr-label">Address Line 1</label>
					<input class="addr-grid-item addr-field-dis" type="text" name="address_line_1" id="addr-line-1" readonly>
				</div>
				<div class="addr-grid-inner-wrapper">
					<label for="addr-line-2" class="addr-label">Line 2</label>
					<input class="addr-grid-item" type="text" name="address_line_2" id="addr-line-2">
				</div>
				<div class="addr-grid-inner-wrapper">
					<label for="addr-line-3" class="addr-label">Line 3</label>
					<input class="addr-grid-item" type="text" name="address_line_3" id="addr-line-3">
				</div>
				<div class="addr-grid-inner-wrapper">
					<label for="addr-city" class="addr-label">City/Town</label>
					<input class="addr-grid-item addr-field-dis" type="text" name="address_city" id="addr-city" readonly>
				</div>
				<div class="addr-grid-inner-wrapper">
					<label for="addr-state" class="addr-label">State/Province</label>
					<input class="addr-grid-item addr-field-dis" type="text" name="address_state" id="addr-state" readonly>
				</div>
				<div class="addr-grid-inner-wrapper">
					<label for="addr-zipcode" class="addr-label">Postal Code</label>
					<input class="addr-grid-item addr-field-dis" type="text" name="address_postal" id="addr-zipcode" readonly>
				</div>
				<div class="addr-grid-inner-wrapper">
					<label for="addr-country" class="addr-label">Country</label>
					<input class="addr-grid-item addr-field-dis" type="text" name="address_country" id="addr-country" readonly>
				</div>
			</div>
			<div id="addr-action-btns">
				<button id="ord-add-site-btn" class="ord-pri-btn" type="submit">Add Site</button>
				<button onclick="toggleSiteBtn(true);" class="ord-pri-btn" type="reset">Clear Form</button>
			</div>
		</form>
	</div>
</section>
<section id="ord-exist-site-sect">
	<h1 class="ord-config-title">Currect Sites</h1>
	{% if siteCount > 0 %}
	<div id="site-list-wrapper">
		{% for site in siteData %}
		<div class="site-row">
			<img onclick="navToBuildPrSite('{{ site.id }}')" style="cursor: pointer;" class="unimp"
				src="{% static 'order/images/icon-60.svg' %}" alt="site-icon">
			{% if site.valid == '0' %}
			<img src="{% static 'icon-102.svg' %}" alt="warn-icon">
			{% else %}
			<img src="{% static 'icon-103.svg' %}" alt="valid-icon">
			{% endif %}
			<span class="tooltip-source">{{ site.name }}
				<span class="tooltip-text">{{ site.addr }}</span>
			</span>
			<span class="unimp-2">{{ site.state }}</span>
			<img onclick="showRmPopup('{{ site.prCount }}', '{{ site.id }}')" src="{% static 'icon-40.svg' %}"
				alt="delete-icon">
		</div>
		{% endfor %}
	</div>
	{% else %}
	<div class="ord-config-subtitle" style="margin: 2rem 0 0 0; padding-left: 1rem;">No sites to display.</div>
	{% endif %}
</section>
<!-- Popup -->
<div class="black-overlay no-show"></div>
<div id="site-del-popup" class="seev-popup no-show">
	<div class="popup-head" style="margin-bottom: 3rem;">
		<img onclick="dismissRmPopup()" src="{% static 'icon-100.svg' %}" alt="close-icon">
	</div>
	<div class="popup-simple-msg"></div>
	<form id="site-del-form" style="display: none;" action="/order/rm-site/" method="post">
		{% csrf_token %}
		<input type="text" name="site-id" id="id_site_id" style="display: none;">
	</form>
	<div style="margin-top: 4rem;" class="popup-action-wrapper">
		<button onclick="confirmDelete()" id="site-del-btn" class="seev-btn-outline seev-icon-btn" type="button">
			<span class="btn-icon-wrapper">
				<span>Remove</span>
				<img class="btn-icon" src="{% static 'icon-104.svg' %}" alt="warn-icon">
			</span>
		</button>
	</div>
</div>
<!-- Scripts -->
<script src="{% static 'order/js/location.js' %}"></script>
<script src="{{ mapApi }}" async defer></script>
{% endblock ordConfBody %}